[doc] Add task_02 SP
brstu/SP-2023 pull request #2
Opened 2023-09-24 17:18 UTC by ValeriaPJul

2023-09-24 21:04 UTC, NogameNo-life requested changes

2023-09-24 21:04 UTC, NogameNo-life commented on tasks/task_02/README.md
> +### Цель работы:
```suggestion
### Цель работы
```

2023-09-24 21:04 UTC, NogameNo-life commented on tasks/task_02/README.md
> +``` c++
```suggestion

``` c++
```

2023-09-24 21:04 UTC, NogameNo-life commented on tasks/task_02/README.md
> +```c++
```suggestion

```c++
```

2023-09-24 21:04 UTC, NogameNo-life commented on tasks/task_02/README.md
> +### Варианты заданий:
```suggestion
### Варианты заданий
```

2023-09-25 14:04 UTC, NogameNo-life commented
Удали каталог .idea

2023-10-03 06:43 UTC, Mkrshkk approved these changes

2023-10-03 11:47 UTC, merged