Lab 02
brstu/SP-2023 pull request #3
Opened 2023-09-24 18:31 UTC by ToxaChiter

2023-09-25 11:40 UTC, OlegSamolyuk requested changes
Задание на защиту: переделать код таким образом, чтобы угадываемое число выбиралось каждый раз случайное.

2023-09-25 18:45 UTC, OlegSamolyuk approved these changes

2023-09-29 08:25 UTC, ToxaChiter commented
Can't really pass the code dup check 'cause of common template project **_:(_**

2023-10-09 06:41 UTC, NogameNo-life approved these changes

2023-10-09 12:15 UTC, KARMA-143 approved these changes

2023-10-16 11:41 UTC, NogameNo-life approved these changes

2023-10-16 11:41 UTC, merged