Add Task_02
brstu/SP-2023 pull request #4
Opened 2023-09-24 20:00 UTC by Mkrshkk

2023-09-25 11:44 UTC, OlegSamolyuk requested changes
Задание на защиту: добавить кнопку обнуления результата.

2023-09-27 13:34 UTC, NogameNo-life requested changes

2023-09-27 13:34 UTC, NogameNo-life commented on trunk/PO210641/task_02/doc/README.md
> +![img_2.png](images/img_2.png)
Код в блоках следует оформлять.

2023-10-03 11:50 UTC, NogameNo-life approved these changes

2023-10-04 10:45 UTC, KARMA-143 approved these changes

2023-10-09 06:40 UTC, merged