Add lab 02
brstu/SP-2023 pull request #5
Opened 2023-09-24 20:21 UTC by KARMA-143

2023-09-25 11:46 UTC, OlegSamolyuk reviewed
Задание на защиту: добавить кнопку, которая будет выводить на одну букву меньше.

2023-09-27 13:41 UTC, NogameNo-life requested changes

2023-09-27 13:41 UTC, NogameNo-life commented on trunk/PO210639/task_02/doc/README.md
> +![img_1](img_1.png)
Код в блоках оформлять.

2023-10-09 06:40 UTC, NogameNo-life approved these changes

2023-10-20 11:24 UTC, NogameNo-life approved these changes

2023-10-20 11:25 UTC, merged