[task_04] add task_04
brstu/SP-2023 pull request #55
Opened 2023-11-25 10:08 UTC by HarWeasttt

2023-12-01 11:11 UTC, AlexaBailey requested changes

2023-12-01 11:11 UTC, AlexaBailey commented on trunk/PO210648/task_04/src/main.cpp
> +    void const changeActiveScreen() {
changeActiveScreen() должна быть const, так как не изменяет значения переменных и объектов, а лишь отвечает за вывод

2023-12-01 11:11 UTC, AlexaBailey commented on trunk/PO210648/task_04/src/main.cpp
> +    bool isShown;
Инициализируй поля isShown и memoryNeeded внутри класса, а не в инициализирующем списке в конструкторе.  строка 11: bool isShown = false;
строка 9: memoryNeeded = 0;

2023-12-15 13:41 UTC, NogameNo-life reviewed
Код в блоках

2023-12-15 13:42 UTC, NogameNo-life requested changes

2023-12-15 13:42 UTC, NogameNo-life commented on trunk/PO210648/task_04/src/CMakeLists.txt
> +add_executable(po8_210648_task_04 WIN32
```suggestion
add_executable(po8_210648_task_04 
```

2023-12-15 19:00 UTC, NogameNo-life approved these changes

2023-12-15 19:01 UTC, merged