[task_07] add task_07
brstu/SP-2023 pull request #61
Opened 2023-12-01 06:46 UTC by HarWeasttt

2023-12-01 13:05 UTC, NogameNo-life requested changes
Код в readme в блоках оформить вместо скриншотов

2023-12-11 05:24 UTC, NogameNo-life requested changes
Где здесь Windows API используется?

2023-12-11 06:12 UTC, HarWeasttt commented
Где я использовал здесь его или зачем его использовать в 7 лабе?

2023-12-13 18:47 UTC, NogameNo-life commented
> Где я использовал здесь его или зачем его использовать в 7 лабе?

Я к тому что в сборке прописана вещь, которая не используется.

2023-12-16 08:55 UTC, NogameNo-life approved these changes

2023-12-16 08:57 UTC, NogameNo-life approved these changes

2023-12-16 08:57 UTC, merged